/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.SanPhamRepository;
import Model.Category;
import Model.Supplier;
import Model.Product;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author TRAN MINH GIAP
 */
public class frmAddProduct extends javax.swing.JFrame {

    /**
     * Creates new form frmAddProduct
     */
    public frmAddProduct() {
        initComponents();
        loadComboboxCategory();
        loadComboboxSupplier();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIDSP = new javax.swing.JLabel();
        lblNameSP = new javax.swing.JLabel();
        lblNhaCC = new javax.swing.JLabel();
        lblLoaiSP = new javax.swing.JLabel();
        lblGiaNhap = new javax.swing.JLabel();
        lblGiaBan = new javax.swing.JLabel();
        btnThemSP = new javax.swing.JButton();
        txtIDSP = new javax.swing.JTextField();
        txtNameSP = new javax.swing.JTextField();
        txtGiaNhap = new javax.swing.JTextField();
        txtGiaBan = new javax.swing.JTextField();
        cbxLoaiSP = new javax.swing.JComboBox<>();
        cbxNCC = new javax.swing.JComboBox<>();
        pnHeader = new javax.swing.JPanel();
        lblHeader = new javax.swing.JLabel();
        btnHuyAddSP = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblIDSP.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblIDSP.setText("Mã Sản Phẩm");

        lblNameSP.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblNameSP.setText("Tên Sản Phẩm");

        lblNhaCC.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblNhaCC.setText("Nhà Cung Cấp");

        lblLoaiSP.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblLoaiSP.setText("Loại Sản Phẩm");

        lblGiaNhap.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblGiaNhap.setText("Giá Nhập");

        lblGiaBan.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblGiaBan.setText("Giá Bán");

        btnThemSP.setBackground(new java.awt.Color(0, 153, 0));
        btnThemSP.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnThemSP.setForeground(new java.awt.Color(255, 255, 255));
        btnThemSP.setText("Thêm Sản Phẩm");
        btnThemSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemSPActionPerformed(evt);
            }
        });

        cbxLoaiSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxLoaiSPActionPerformed(evt);
            }
        });

        pnHeader.setBackground(new java.awt.Color(0, 153, 0));

        lblHeader.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblHeader.setForeground(new java.awt.Color(255, 255, 255));
        lblHeader.setText("Nhập Thông Tin Sản Phẩm");

        javax.swing.GroupLayout pnHeaderLayout = new javax.swing.GroupLayout(pnHeader);
        pnHeader.setLayout(pnHeaderLayout);
        pnHeaderLayout.setHorizontalGroup(
            pnHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHeaderLayout.createSequentialGroup()
                .addComponent(lblHeader)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnHeaderLayout.setVerticalGroup(
            pnHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHeaderLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblHeader)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        btnHuyAddSP.setBackground(new java.awt.Color(0, 153, 0));
        btnHuyAddSP.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnHuyAddSP.setForeground(new java.awt.Color(255, 255, 255));
        btnHuyAddSP.setText("Hủy");
        btnHuyAddSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyAddSPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnThemSP)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblNameSP)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNameSP, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblNhaCC)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbxNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblIDSP)
                            .addGap(30, 30, 30)
                            .addComponent(txtIDSP, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLoaiSP)
                            .addComponent(lblGiaNhap)
                            .addComponent(lblGiaBan))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbxLoaiSP, 0, 200, Short.MAX_VALUE)
                            .addComponent(txtGiaNhap)
                            .addComponent(txtGiaBan)))
                    .addComponent(btnHuyAddSP, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIDSP)
                    .addComponent(lblLoaiSP)
                    .addComponent(txtIDSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxLoaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNameSP)
                    .addComponent(txtNameSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGiaNhap)
                    .addComponent(txtGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGiaBan)
                    .addComponent(lblNhaCC)
                    .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemSP, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHuyAddSP, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void resetText(){
        txtIDSP.setText("");
        txtNameSP.setText("");
        txtGiaNhap.setText("");
        txtGiaBan.setText("");
        cbxLoaiSP.setSelectedIndex(-1);
        cbxNCC.setSelectedIndex(-1);
    }
    public void loadComboboxSupplier(){
        SanPhamRepository spReposytory = new SanPhamRepository();
        List<Supplier> lstSL = spReposytory.getcomboboxSupplier();
        cbxNCC.removeAllItems();
        for(int i = 0 ; i < lstSL.size() ; i++){
            cbxNCC.addItem(lstSL.get(i));
        }
    }
    public void loadComboboxCategory(){
        SanPhamRepository spReposytory = new SanPhamRepository();
        List<Category> lst = spReposytory.getComboboxCategory();
        int tmp = lst.size();
        cbxLoaiSP.removeAllItems();
        for(int i = 0 ; i < lst.size() ; i++){
            cbxLoaiSP.addItem(lst.get(i));
        }
    }
    private void btnThemSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemSPActionPerformed
        // TODO add your handling code here:
        String id = txtIDSP.getText();
        String name = txtNameSP.getText();
        String priceNhap = txtGiaNhap.getText();
        String priceBan = txtGiaBan.getText();
        Category ctg = (Category)cbxLoaiSP.getSelectedItem();
        Supplier sup = (Supplier)cbxNCC.getSelectedItem();
        int num = 0;

        if(id.equals("") || name.equals("") || priceNhap.equals("") || priceBan.equals("")){
            JOptionPane.showMessageDialog(this, "Please input all data to add product !");
            return;
        }

        try {
            float tmp1 = Float.parseFloat(priceNhap);
            float tmp2 = Float.parseFloat(priceBan);
            if(tmp1 <= 0 || tmp2 <= 0){
                JOptionPane.showMessageDialog(this, "VALIDATE Price ! ");
                return;
            }
    
            Product pr = new Product(id, name, tmp1, tmp2, num, ctg.getCategoryID(), sup.getSupplierID());
            SanPhamRepository rp = new SanPhamRepository();
            if(rp.addProduct(pr)){
                JOptionPane.showMessageDialog(this, "ADD Product SUCCESSFULL !");
            }
            else{
                JOptionPane.showMessageDialog(this, "ADD Product Failed !");
            }
            resetText();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "VALIDATE Price ! " + ex.getMessage());
        }
        this.dispose();
    }//GEN-LAST:event_btnThemSPActionPerformed

    private void cbxLoaiSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxLoaiSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxLoaiSPActionPerformed

    private void btnHuyAddSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyAddSPActionPerformed
        // TODO add your handling code here:
        resetText();
        JOptionPane.showMessageDialog(this, "PRODUCT NOT ADDED TO LIST !");
        this.dispose();
    }//GEN-LAST:event_btnHuyAddSPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAddProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuyAddSP;
    private javax.swing.JButton btnThemSP;
    private javax.swing.JComboBox<Category> cbxLoaiSP;
    private javax.swing.JComboBox<Supplier> cbxNCC;
    private javax.swing.JLabel lblGiaBan;
    private javax.swing.JLabel lblGiaNhap;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblIDSP;
    private javax.swing.JLabel lblLoaiSP;
    private javax.swing.JLabel lblNameSP;
    private javax.swing.JLabel lblNhaCC;
    private javax.swing.JPanel pnHeader;
    private javax.swing.JTextField txtGiaBan;
    private javax.swing.JTextField txtGiaNhap;
    private javax.swing.JTextField txtIDSP;
    private javax.swing.JTextField txtNameSP;
    // End of variables declaration//GEN-END:variables
}
