/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Controller.SanPhamRepository;
import Model.Product;
import java.awt.Window;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TRAN MINH GIAP
 */
public class pnAddProductInCart extends javax.swing.JPanel {
    private Product pr = new Product();
    private DefaultTableModel tbmTmp = new DefaultTableModel();
    private boolean check = false;
    /**
     * Creates new form pnAddProductInCart
     */
    /*Có thể sử dụng hàm khởi tạo để truyền dữ liệu*/
    public pnAddProductInCart() {
        initComponents();
        Spiner.setValue(1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblChiTietID = new javax.swing.JLabel();
        lblChiTietThuongHieu = new javax.swing.JLabel();
        lblChiTietSoLuong = new javax.swing.JLabel();
        lblShowThuongHieu = new javax.swing.JLabel();
        Spiner = new javax.swing.JSpinner();
        btnAddToCart = new javax.swing.JButton();
        btnDestroy = new javax.swing.JButton();
        lblShowIDSP = new javax.swing.JLabel();
        lblGiaDangBan = new javax.swing.JLabel();
        txtGiaDangBan = new javax.swing.JLabel();
        lblTongTienChiTietHoaDon = new javax.swing.JLabel();
        txtTongTienChiTietHoaDon = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(0, 153, 0));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sản Phẩm ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(17, 17, 17))
        );

        lblChiTietID.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lblChiTietID.setText("Mã Sản Phẩm");

        lblChiTietThuongHieu.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lblChiTietThuongHieu.setText("Thương Hiệu");

        lblChiTietSoLuong.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lblChiTietSoLuong.setText("Số Lượng");

        lblShowThuongHieu.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N

        Spiner.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        Spiner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SpinerStateChanged(evt);
            }
        });

        btnAddToCart.setBackground(new java.awt.Color(0, 153, 0));
        btnAddToCart.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnAddToCart.setForeground(new java.awt.Color(255, 255, 255));
        btnAddToCart.setText("Add To Cart");
        btnAddToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddToCartActionPerformed(evt);
            }
        });

        btnDestroy.setBackground(new java.awt.Color(0, 153, 0));
        btnDestroy.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnDestroy.setForeground(new java.awt.Color(255, 255, 255));
        btnDestroy.setText("Destroy");
        btnDestroy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDestroyActionPerformed(evt);
            }
        });

        lblShowIDSP.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N

        lblGiaDangBan.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lblGiaDangBan.setText("Giá Đang Bán");

        txtGiaDangBan.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N

        lblTongTienChiTietHoaDon.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lblTongTienChiTietHoaDon.setText("Tổng Tiền");

        txtTongTienChiTietHoaDon.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(lblChiTietThuongHieu))
                            .addComponent(lblChiTietID))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblShowIDSP, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblShowThuongHieu, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(lblGiaDangBan)
                        .addGap(18, 18, 18)
                        .addComponent(txtGiaDangBan, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(btnAddToCart)
                .addGap(18, 18, 18)
                .addComponent(btnDestroy, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTongTienChiTietHoaDon)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(lblChiTietSoLuong)
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTongTienChiTietHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Spiner, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblChiTietID)
                    .addComponent(lblShowIDSP, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblChiTietThuongHieu)
                    .addComponent(lblShowThuongHieu, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGiaDangBan, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtGiaDangBan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblChiTietSoLuong)
                    .addComponent(Spiner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTongTienChiTietHoaDon)
                    .addComponent(txtTongTienChiTietHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddToCart, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDestroy, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDestroyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDestroyActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Sản Phẩm Không Được Thêm Vào Giỏ Hàng");
        destroy();
    }//GEN-LAST:event_btnDestroyActionPerformed
    
    private void btnAddToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToCartActionPerformed
        // TODO add your handling code here:
        SanPhamRepository sprepo = new SanPhamRepository();
        int value = (int) Spiner.getValue();  // SL MUA
        double price = (double)pr.getProductPriceOut();// GIA BAN TREN 1 SP
        String productType = sprepo.getNameCategory(pr.getCategoryID());
        String supplierName = sprepo.getNameSuppier(pr.getSupplierID());
        double total = (double)(price * value);
        if(value <= 0){
            JOptionPane.showMessageDialog(this, "Nhập Số Lượng Sản Phẩm Muốn Mua !");
            return;
        }
        try {
            tbmTmp.addRow(new Object[]{pr.getProductID(), pr.getProductName(), value, price, productType, supplierName, total});
            JOptionPane.showMessageDialog(this, "Đã Thêm Sản Phẩm Vào Giỏ Hàng !");
        } catch (Exception ex) {
            System.out.println("Error event btnAddToCart in pnAddProductInCart : " + ex.getMessage());
        }
        destroy();
    }//GEN-LAST:event_btnAddToCartActionPerformed

    private void SpinerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SpinerStateChanged
        // TODO add your handling code here:
        if(check == true){
            int value = (int) Spiner.getValue();
            if(value > this.pr.getQuantity()){
//                System.out.println("value : pr.getQuantity : " + value + " : " + pr.getQuantity());
                JOptionPane.showMessageDialog(this, "Số Lượng Sản Phẩm Vượt Quá Giới Hạn");
                Spiner.setValue(pr.getQuantity());
            }
            double total = (double) this.pr.getProductPriceOut() * value;
            txtTongTienChiTietHoaDon.setText(String.valueOf(total) + " VNĐ");
        }
    }//GEN-LAST:event_SpinerStateChanged
    /*******************************************************/
    public void destroy(){
        Window window = SwingUtilities.windowForComponent(this);
        if (window != null) {
            window.dispose(); // Đóng JDialog
        }
    }
    void showDataProduct(Product pr, DefaultTableModel tbmCart){
        SanPhamRepository sprepo = new SanPhamRepository();
        this.lblShowIDSP.setText(pr.getProductID());
        this.lblShowThuongHieu.setText(sprepo.getNameSuppier(pr.getSupplierID()));
        this.txtGiaDangBan.setText(String.valueOf(pr.getProductPriceOut()) + " VND");
        this.txtTongTienChiTietHoaDon.setText(String.valueOf(pr.getProductPriceOut()) + "VND");
        this.pr = pr;
        this.tbmTmp = tbmCart;
        this.check = true;
    }
    /*******************************************************/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner Spiner;
    private javax.swing.JButton btnAddToCart;
    private javax.swing.JButton btnDestroy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblChiTietID;
    private javax.swing.JLabel lblChiTietSoLuong;
    private javax.swing.JLabel lblChiTietThuongHieu;
    private javax.swing.JLabel lblGiaDangBan;
    private javax.swing.JLabel lblShowIDSP;
    private javax.swing.JLabel lblShowThuongHieu;
    private javax.swing.JLabel lblTongTienChiTietHoaDon;
    private javax.swing.JLabel txtGiaDangBan;
    private javax.swing.JLabel txtTongTienChiTietHoaDon;
    // End of variables declaration//GEN-END:variables
}
