/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Controller.SanPhamRepository;
import Model.Category;
import java.awt.Window;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author TRAN MINH GIAP
 */
public class pnAddDMSP extends javax.swing.JPanel {

    /**
     * Creates new form pnAddDMSP
     */
    public pnAddDMSP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnHeader = new javax.swing.JPanel();
        lblHeader = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblDESC = new javax.swing.JLabel();
        btnAddDMSP = new javax.swing.JButton();
        btnHuyDMSP = new javax.swing.JButton();
        txtID = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaDESC = new javax.swing.JTextArea();

        pnHeader.setBackground(new java.awt.Color(0, 153, 0));

        lblHeader.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        lblHeader.setForeground(new java.awt.Color(255, 255, 255));
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("Thêm Danh Mục Sản Phẩm");

        javax.swing.GroupLayout pnHeaderLayout = new javax.swing.GroupLayout(pnHeader);
        pnHeader.setLayout(pnHeaderLayout);
        pnHeaderLayout.setHorizontalGroup(
            pnHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnHeaderLayout.setVerticalGroup(
            pnHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnHeaderLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(lblHeader)
                .addGap(14, 14, 14))
        );

        lblID.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lblID.setText("ID");

        lblName.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lblName.setText("NAME");

        lblDESC.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lblDESC.setText("DESC");

        btnAddDMSP.setBackground(new java.awt.Color(0, 153, 0));
        btnAddDMSP.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnAddDMSP.setForeground(new java.awt.Color(255, 255, 255));
        btnAddDMSP.setText("Thêm");
        btnAddDMSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDMSPActionPerformed(evt);
            }
        });

        btnHuyDMSP.setBackground(new java.awt.Color(0, 153, 0));
        btnHuyDMSP.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnHuyDMSP.setForeground(new java.awt.Color(255, 255, 255));
        btnHuyDMSP.setText("Hủy");
        btnHuyDMSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyDMSPActionPerformed(evt);
            }
        });

        txtID.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N

        txtName.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N

        txtaDESC.setColumns(20);
        txtaDESC.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        txtaDESC.setRows(5);
        jScrollPane1.setViewportView(txtaDESC);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblID)
                    .addComponent(lblName)
                    .addComponent(lblDESC))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                    .addComponent(txtName)
                    .addComponent(txtID))
                .addContainerGap(94, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddDMSP, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btnHuyDMSP, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDESC)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddDMSP, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHuyDMSP, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddDMSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDMSPActionPerformed
        // TODO add your handling code here:
        String id = txtID.getText();
        String name = txtName.getText();
        String desc = txtaDESC.getText();
        if(id.equals("") || name.equals("")){
            JOptionPane.showMessageDialog(this, "Nhập Đầy Đủ Thông Tin Danh Mục Sản Phẩm Muốn Thêm !");
            return;
        }
        try {
            SanPhamRepository sprepo = new SanPhamRepository();
            Category ctg = new Category(id, name, desc);
            if(sprepo.addCategory(ctg)){
                JOptionPane.showMessageDialog(this, "Thêm Danh Mục < Loại > Sản Phẩm Thành Công !");
                destroy();
            }
            else{
                JOptionPane.showMessageDialog(this, "Thêm Danh Mục < Loại > Sản Phẩm Thất Bại !");
            }
        } catch (Exception ex) {
            System.out.println("ERROR EVEN btnAddDMSP : " + ex.getMessage());
        }
    }//GEN-LAST:event_btnAddDMSPActionPerformed

    private void btnHuyDMSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyDMSPActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Danh Mục Sản Phẩm Không Được Thêm !");
        destroy();
    }//GEN-LAST:event_btnHuyDMSPActionPerformed
    
    /****************************************************/
    public void destroy(){
        Window window = SwingUtilities.windowForComponent(this);
        if (window != null) {
            window.dispose();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDMSP;
    private javax.swing.JButton btnHuyDMSP;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDESC;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblName;
    private javax.swing.JPanel pnHeader;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextArea txtaDESC;
    // End of variables declaration//GEN-END:variables
}
