/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TRAN MINH GIAP
 */
public class ShoppingCart extends javax.swing.JPanel {
    DefaultTableModel tbmShoppingCart = new DefaultTableModel();
    /**
     * Creates new form ShoppingCart
     */
    public ShoppingCart() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    /***************************************************************************/
    /*Gọi để tham chiếu đến sản phầm được thêm vào giỏ hàng*/
    public void showData(DefaultTableModel tbmCart){
        int tongSL = 0;
        double tongTien = 0;
        this.tbmShoppingCart = tbmCart;
        tbShoppingCart.setModel(tbmShoppingCart);
        try {
            for(int i = 0 ; i < tbShoppingCart.getRowCount() ; i++){
                tongTien += (double)tbShoppingCart.getValueAt(i, 6);
            }
            lblTongTienBanDau.setText(String.valueOf(tongTien));
            
        } catch (Exception ex) {
            System.out.println("Error Funtion ShơwData in ShoppingCart");
        }
    }
    /*Hiển thị lên bảng*/
    /***************************************************************************/
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnHeaderShoppingCart = new javax.swing.JPanel();
        lblHeaderShoppingCart = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbShoppingCart = new javax.swing.JTable();
        pnCustomerShoppingCart = new javax.swing.JPanel();
        lblTitleCusShoppingCart = new javax.swing.JLabel();
        lblIDCusShoppingCart = new javax.swing.JLabel();
        lblNameCusShoppingCart = new javax.swing.JLabel();
        lblAddressCusShoppingCart = new javax.swing.JLabel();
        lblPhoneCusShoppingCart = new javax.swing.JLabel();
        txtIDShoppingCart = new javax.swing.JTextField();
        txtNameCusShoppingCart = new javax.swing.JTextField();
        txtAddressCusShoppingCart = new javax.swing.JTextField();
        txtPhoneCusShoppingCard = new javax.swing.JTextField();
        pnPayShoppingCart = new javax.swing.JPanel();
        lblTongCongShoppingCart = new javax.swing.JLabel();
        lblSaleShoppingCart = new javax.swing.JLabel();
        lblThanhTienShoppingCard = new javax.swing.JLabel();
        lblKhachTraShoppingCart = new javax.swing.JLabel();
        lblTraLaiShoppingCart = new javax.swing.JLabel();
        btnHoanTatShoppingCart = new javax.swing.JButton();
        btnHuyShoppingCart = new javax.swing.JButton();
        lblTongTienBanDau = new javax.swing.JLabel();
        lblThanhTienThanhToan = new javax.swing.JLabel();
        lblNumTraLai = new javax.swing.JLabel();
        lblNumThanhToan = new javax.swing.JLabel();
        txtNumberSale = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 255, 204));

        pnHeaderShoppingCart.setBackground(new java.awt.Color(0, 153, 0));

        lblHeaderShoppingCart.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblHeaderShoppingCart.setForeground(new java.awt.Color(255, 255, 255));
        lblHeaderShoppingCart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeaderShoppingCart.setText("Shopping Cart");

        javax.swing.GroupLayout pnHeaderShoppingCartLayout = new javax.swing.GroupLayout(pnHeaderShoppingCart);
        pnHeaderShoppingCart.setLayout(pnHeaderShoppingCartLayout);
        pnHeaderShoppingCartLayout.setHorizontalGroup(
            pnHeaderShoppingCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHeaderShoppingCart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnHeaderShoppingCartLayout.setVerticalGroup(
            pnHeaderShoppingCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHeaderShoppingCartLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblHeaderShoppingCart)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        tbShoppingCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã SP", "Tên SP", "SL Mua", "Đơn Giá", "Loại SP", "Nhà Cung Cấp", "Tổng Tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbShoppingCart);

        pnCustomerShoppingCart.setBackground(new java.awt.Color(255, 255, 255));
        pnCustomerShoppingCart.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblTitleCusShoppingCart.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblTitleCusShoppingCart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleCusShoppingCart.setText("Nhập Thông Tin Khách Hàng");

        lblIDCusShoppingCart.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        lblIDCusShoppingCart.setText("Mã Khách Hàng");

        lblNameCusShoppingCart.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        lblNameCusShoppingCart.setText("Tên Khách Hàng");

        lblAddressCusShoppingCart.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        lblAddressCusShoppingCart.setText("Địa Chỉ");

        lblPhoneCusShoppingCart.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        lblPhoneCusShoppingCart.setText("Số Điện Thoại");

        javax.swing.GroupLayout pnCustomerShoppingCartLayout = new javax.swing.GroupLayout(pnCustomerShoppingCart);
        pnCustomerShoppingCart.setLayout(pnCustomerShoppingCartLayout);
        pnCustomerShoppingCartLayout.setHorizontalGroup(
            pnCustomerShoppingCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitleCusShoppingCart, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
            .addGroup(pnCustomerShoppingCartLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pnCustomerShoppingCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNameCusShoppingCart)
                    .addComponent(lblIDCusShoppingCart)
                    .addComponent(lblAddressCusShoppingCart, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPhoneCusShoppingCart, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(30, 30, 30)
                .addGroup(pnCustomerShoppingCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNameCusShoppingCart)
                    .addComponent(txtIDShoppingCart)
                    .addComponent(txtAddressCusShoppingCart)
                    .addComponent(txtPhoneCusShoppingCard, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnCustomerShoppingCartLayout.setVerticalGroup(
            pnCustomerShoppingCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCustomerShoppingCartLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblTitleCusShoppingCart)
                .addGap(18, 18, 18)
                .addGroup(pnCustomerShoppingCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIDCusShoppingCart)
                    .addComponent(txtIDShoppingCart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(pnCustomerShoppingCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNameCusShoppingCart)
                    .addComponent(txtNameCusShoppingCart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(pnCustomerShoppingCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddressCusShoppingCart)
                    .addComponent(txtAddressCusShoppingCart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(pnCustomerShoppingCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPhoneCusShoppingCart)
                    .addComponent(txtPhoneCusShoppingCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        pnPayShoppingCart.setBackground(new java.awt.Color(255, 255, 255));
        pnPayShoppingCart.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblTongCongShoppingCart.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        lblTongCongShoppingCart.setText("Tổng Cộng");

        lblSaleShoppingCart.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        lblSaleShoppingCart.setText("Sale (%)");

        lblThanhTienShoppingCard.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        lblThanhTienShoppingCard.setText("Thành Tiền");

        lblKhachTraShoppingCart.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        lblKhachTraShoppingCart.setText("Khách Trả");

        lblTraLaiShoppingCart.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        lblTraLaiShoppingCart.setText("Trả Lại");

        btnHoanTatShoppingCart.setBackground(new java.awt.Color(0, 153, 0));
        btnHoanTatShoppingCart.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btnHoanTatShoppingCart.setForeground(new java.awt.Color(255, 255, 255));
        btnHoanTatShoppingCart.setText("Hoàn Tất");

        btnHuyShoppingCart.setBackground(new java.awt.Color(0, 153, 0));
        btnHuyShoppingCart.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btnHuyShoppingCart.setForeground(new java.awt.Color(255, 255, 255));
        btnHuyShoppingCart.setText("Hủy");

        txtNumberSale.setBorder(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Chi Tiết Thanh Toán");

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout pnPayShoppingCartLayout = new javax.swing.GroupLayout(pnPayShoppingCart);
        pnPayShoppingCart.setLayout(pnPayShoppingCartLayout);
        pnPayShoppingCartLayout.setHorizontalGroup(
            pnPayShoppingCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPayShoppingCartLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnPayShoppingCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnPayShoppingCartLayout.createSequentialGroup()
                        .addGroup(pnPayShoppingCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblThanhTienShoppingCard)
                            .addComponent(lblKhachTraShoppingCart))
                        .addGap(16, 16, 16)
                        .addGroup(pnPayShoppingCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnPayShoppingCartLayout.createSequentialGroup()
                                .addComponent(lblThanhTienThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(357, Short.MAX_VALUE))
                            .addGroup(pnPayShoppingCartLayout.createSequentialGroup()
                                .addComponent(lblNumThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 357, Short.MAX_VALUE))))
                    .addGroup(pnPayShoppingCartLayout.createSequentialGroup()
                        .addGroup(pnPayShoppingCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSaleShoppingCart)
                            .addComponent(lblTongCongShoppingCart))
                        .addGroup(pnPayShoppingCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnPayShoppingCartLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(pnPayShoppingCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblTongTienBanDau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtNumberSale, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)))
                            .addGroup(pnPayShoppingCartLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel2)))
                        .addContainerGap())
                    .addGroup(pnPayShoppingCartLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(pnPayShoppingCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnPayShoppingCartLayout.createSequentialGroup()
                                .addComponent(lblTraLaiShoppingCart)
                                .addGap(16, 16, 16)
                                .addComponent(lblNumTraLai, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(pnPayShoppingCartLayout.createSequentialGroup()
                                .addComponent(btnHoanTatShoppingCart)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnHuyShoppingCart, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34))))))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnPayShoppingCartLayout.setVerticalGroup(
            pnPayShoppingCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPayShoppingCartLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnPayShoppingCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTongCongShoppingCart)
                    .addComponent(lblTongTienBanDau)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(pnPayShoppingCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSaleShoppingCart)
                    .addComponent(txtNumberSale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(pnPayShoppingCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblThanhTienShoppingCard)
                    .addComponent(lblThanhTienThanhToan))
                .addGap(18, 18, 18)
                .addGroup(pnPayShoppingCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKhachTraShoppingCart)
                    .addComponent(lblNumThanhToan))
                .addGap(18, 18, 18)
                .addGroup(pnPayShoppingCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTraLaiShoppingCart)
                    .addComponent(lblNumTraLai))
                .addGap(18, 18, 18)
                .addGroup(pnPayShoppingCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHoanTatShoppingCart)
                    .addComponent(btnHuyShoppingCart))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnHeaderShoppingCart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnCustomerShoppingCart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnPayShoppingCart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnHeaderShoppingCart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnCustomerShoppingCart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnPayShoppingCart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHoanTatShoppingCart;
    private javax.swing.JButton btnHuyShoppingCart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddressCusShoppingCart;
    private javax.swing.JLabel lblHeaderShoppingCart;
    private javax.swing.JLabel lblIDCusShoppingCart;
    private javax.swing.JLabel lblKhachTraShoppingCart;
    private javax.swing.JLabel lblNameCusShoppingCart;
    private javax.swing.JLabel lblNumThanhToan;
    private javax.swing.JLabel lblNumTraLai;
    private javax.swing.JLabel lblPhoneCusShoppingCart;
    private javax.swing.JLabel lblSaleShoppingCart;
    private javax.swing.JLabel lblThanhTienShoppingCard;
    private javax.swing.JLabel lblThanhTienThanhToan;
    private javax.swing.JLabel lblTitleCusShoppingCart;
    private javax.swing.JLabel lblTongCongShoppingCart;
    private javax.swing.JLabel lblTongTienBanDau;
    private javax.swing.JLabel lblTraLaiShoppingCart;
    private javax.swing.JPanel pnCustomerShoppingCart;
    private javax.swing.JPanel pnHeaderShoppingCart;
    private javax.swing.JPanel pnPayShoppingCart;
    private javax.swing.JTable tbShoppingCart;
    private javax.swing.JTextField txtAddressCusShoppingCart;
    private javax.swing.JTextField txtIDShoppingCart;
    private javax.swing.JTextField txtNameCusShoppingCart;
    private javax.swing.JTextField txtNumberSale;
    private javax.swing.JTextField txtPhoneCusShoppingCard;
    // End of variables declaration//GEN-END:variables
}
